FLAGS    = -z execstack  # -fno-stack-protector
FLAGS_32 = -m32
TARGET   = stack-L1-stackguard
 

L1 = 100
 
all: $(TARGET)

stack-L1-stackguard: stack.c
	gcc -DBUF_SIZE=$(L1) $(FLAGS) $(FLAGS_32) -o $@ stack.c
	sudo chown root $@ && sudo chmod 4755 $@

